# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hamzalah/Documents/gitProjects/BirdFlock/BirdFlock

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hamzalah/Documents/gitProjects/BirdFlock/BirdFlock

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hamzalah/Documents/gitProjects/BirdFlock/BirdFlock/CMakeFiles /Users/hamzalah/Documents/gitProjects/BirdFlock/BirdFlock//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hamzalah/Documents/gitProjects/BirdFlock/BirdFlock/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BirdFLock

# Build rule for target.
BirdFLock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BirdFLock
.PHONY : BirdFLock

# fast build rule for target.
BirdFLock/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/build
.PHONY : BirdFLock/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/main.cpp.s
.PHONY : main.cpp.s

newVulkanApp.o: newVulkanApp.cpp.o

.PHONY : newVulkanApp.o

# target to build an object file
newVulkanApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/newVulkanApp.cpp.o
.PHONY : newVulkanApp.cpp.o

newVulkanApp.i: newVulkanApp.cpp.i

.PHONY : newVulkanApp.i

# target to preprocess a source file
newVulkanApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/newVulkanApp.cpp.i
.PHONY : newVulkanApp.cpp.i

newVulkanApp.s: newVulkanApp.cpp.s

.PHONY : newVulkanApp.s

# target to generate assembly for a file
newVulkanApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/newVulkanApp.cpp.s
.PHONY : newVulkanApp.cpp.s

vulkanDevice.o: vulkanDevice.cpp.o

.PHONY : vulkanDevice.o

# target to build an object file
vulkanDevice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/vulkanDevice.cpp.o
.PHONY : vulkanDevice.cpp.o

vulkanDevice.i: vulkanDevice.cpp.i

.PHONY : vulkanDevice.i

# target to preprocess a source file
vulkanDevice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/vulkanDevice.cpp.i
.PHONY : vulkanDevice.cpp.i

vulkanDevice.s: vulkanDevice.cpp.s

.PHONY : vulkanDevice.s

# target to generate assembly for a file
vulkanDevice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/vulkanDevice.cpp.s
.PHONY : vulkanDevice.cpp.s

vulkanModel.o: vulkanModel.cpp.o

.PHONY : vulkanModel.o

# target to build an object file
vulkanModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/vulkanModel.cpp.o
.PHONY : vulkanModel.cpp.o

vulkanModel.i: vulkanModel.cpp.i

.PHONY : vulkanModel.i

# target to preprocess a source file
vulkanModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/vulkanModel.cpp.i
.PHONY : vulkanModel.cpp.i

vulkanModel.s: vulkanModel.cpp.s

.PHONY : vulkanModel.s

# target to generate assembly for a file
vulkanModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/vulkanModel.cpp.s
.PHONY : vulkanModel.cpp.s

vulkanPipeline.o: vulkanPipeline.cpp.o

.PHONY : vulkanPipeline.o

# target to build an object file
vulkanPipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/vulkanPipeline.cpp.o
.PHONY : vulkanPipeline.cpp.o

vulkanPipeline.i: vulkanPipeline.cpp.i

.PHONY : vulkanPipeline.i

# target to preprocess a source file
vulkanPipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/vulkanPipeline.cpp.i
.PHONY : vulkanPipeline.cpp.i

vulkanPipeline.s: vulkanPipeline.cpp.s

.PHONY : vulkanPipeline.s

# target to generate assembly for a file
vulkanPipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/vulkanPipeline.cpp.s
.PHONY : vulkanPipeline.cpp.s

vulkanSwapChain.o: vulkanSwapChain.cpp.o

.PHONY : vulkanSwapChain.o

# target to build an object file
vulkanSwapChain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/vulkanSwapChain.cpp.o
.PHONY : vulkanSwapChain.cpp.o

vulkanSwapChain.i: vulkanSwapChain.cpp.i

.PHONY : vulkanSwapChain.i

# target to preprocess a source file
vulkanSwapChain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/vulkanSwapChain.cpp.i
.PHONY : vulkanSwapChain.cpp.i

vulkanSwapChain.s: vulkanSwapChain.cpp.s

.PHONY : vulkanSwapChain.s

# target to generate assembly for a file
vulkanSwapChain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/vulkanSwapChain.cpp.s
.PHONY : vulkanSwapChain.cpp.s

vulkanWindow.o: vulkanWindow.cpp.o

.PHONY : vulkanWindow.o

# target to build an object file
vulkanWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/vulkanWindow.cpp.o
.PHONY : vulkanWindow.cpp.o

vulkanWindow.i: vulkanWindow.cpp.i

.PHONY : vulkanWindow.i

# target to preprocess a source file
vulkanWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/vulkanWindow.cpp.i
.PHONY : vulkanWindow.cpp.i

vulkanWindow.s: vulkanWindow.cpp.s

.PHONY : vulkanWindow.s

# target to generate assembly for a file
vulkanWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BirdFLock.dir/build.make CMakeFiles/BirdFLock.dir/vulkanWindow.cpp.s
.PHONY : vulkanWindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BirdFLock"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... newVulkanApp.o"
	@echo "... newVulkanApp.i"
	@echo "... newVulkanApp.s"
	@echo "... vulkanDevice.o"
	@echo "... vulkanDevice.i"
	@echo "... vulkanDevice.s"
	@echo "... vulkanModel.o"
	@echo "... vulkanModel.i"
	@echo "... vulkanModel.s"
	@echo "... vulkanPipeline.o"
	@echo "... vulkanPipeline.i"
	@echo "... vulkanPipeline.s"
	@echo "... vulkanSwapChain.o"
	@echo "... vulkanSwapChain.i"
	@echo "... vulkanSwapChain.s"
	@echo "... vulkanWindow.o"
	@echo "... vulkanWindow.i"
	@echo "... vulkanWindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

